---
name: Publish Docker image

# TODO: currently pushes to registry on every push.
# But it is preferrable to run on releases
# on:
#   release:
#     types:
#       [published]
"on":
  push:
    branches: [main]
concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Log in to Github Image Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/${{ github.repository_owner }}/opendebate-api
          tags: |
            type=raw,value=main,enable={{is_default_branch}}
            type=sha,prefix=sha-,format=short
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: mode=max
          sbom: true
      - name: Generate artifact attestation
        if: ${{ !env.ACT }}
        uses: actions/attest-build-provenance@v4
        with:
          subject-name: ghcr.io/${{ github.repository_owner }}/opendebate-api
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

  bump-manifest:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          repository: Ukrainian-Debate-Dev-Community/opendebate-k8s
          token: ${{ secrets.K8S_REPO_TOKEN }}
      - name: Set up kustomize
        uses: imranismail/setup-kustomize@v3
      - name: Bump image tag
        run: |
          SHORT_SHA="$(echo ${{ github.sha }} | cut -c1-7)"
          IMAGE="ghcr.io/ukrainian-debate-dev-community/opendebate-api"
          cd apps/api
          kustomize edit set image "${IMAGE}=${IMAGE}:sha-${SHORT_SHA}"
      - name: Commit & push
        run: |
          git config user.name  "opendebate-bot"
          git config user.email "bot@users.noreply.github.com"
          git add apps/api/kustomization.yaml
          MSG="chore(api): bump image to sha-${GITHUB_SHA::7}"
          git diff --cached --quiet || git commit -m "${MSG}"
          git push
